name: BetterEnchants
author: AlexTheCoder
version: 2.8
main: me.AlexTheCoder.BetterEnchants.Main
softdepend: [ProjectKorra, WorldGuard]
commands:
  betterenchants:
    aliases: [be]
    usage: /<command>
  addenchant:
    usage: /<command> <EnchantName> <Level>
  getcrystal:
    usage: /<command> <EnchantName> <Level>
  givecrystal:
    usage: /<command> <EnchantName> <Level> <Player>